#!/bin/bash
src=src
main=softsrv.cpp
out=bin/softsrv
flags="-Wall -pedantic"
file_list=(
  "$main"
  core/platform.cpp 
  core/framebuffer.cpp 
  core/draw.cpp 
  core/image.cpp
)

case "$OSTYPE" in
  darwin*) # OSX
    file_list+=("system/osx.m")
    sys_flags="-framework Cocoa" 
  ;; 
  msys*|cygwin*) # Windows
    file_list+=("system/win.c")
    sys_flags="-lgdi32"
  ;;
  # linux*)   echo "LINUX" ;; # TODO
  *)        echo "unknown: $OSTYPE" ;;
esac

printf "\n"
for f in "${file_list[@]}"; do
  printf "%s\n" "$f"
  files="$src/$f $files"
done

flags="$flags $sys_flags -O3"
cmd="clang -o $out $files $flags"

printf "\n%s\n" "$cmd"

printf "\nbuilding...\n"
if $cmd
then
  echo "success"
  if [ "$1" = "run" ]
  then
    printf "\nrunning %s\n\n" "$out"
    printf "[program output]\n"
    $out
  fi
fi